### DISCUSSION TITLE
What kafka image are you using?

### DISCUSSION THREAD

**Discussion by extreme4all** [airtai/fastkafka#4] [Q&A] [answered]
i'm using the following

docker-compose.yml
```
version: '3'
services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
    volumes:
      - ./kafka:/bitnami/kafka:rw
    ports:
      - 9094:9094
```
